services:
    - docker

env:
    global:
        - COMMIT=${TRAVIS_COMMIT::8}

before_install:
    - docker-compose -f docker-compose-tests.yml build
    - export VERSION=$(curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
    - wget https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
    - tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz

script:
    - ./trivy --exit-code 1 --severity HIGH --ignore-unfixed --no-progress jwt_boilerplate_web
    - ./trivy --exit-code 1 --severity CRITICAL --ignore-unfixed --no-progress jwt_boilerplate_web
    - docker-compose -f docker-compose-tests.yml up --exit-code-from web
