# docker-compose -f docker-compose-tests.yml up --exit-code-from web

version: '3.8'
services:
  web:
    build: ./web
    command: python tests.py
    volumes:
      - ./web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.test
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.test.db
volumes:
  postgres_data:
