# docker-compose -f docker-compose-tests.yml up --exit-code-from auth --build

version: '3.3'
services:
  auth:
    build: ./auth
    command: pipenv run python tests.py
    environment:
      - FLASK_APP=app/__init__.py
      - FLASK_ENV=testing
      - DATABASE_URL=postgresql://test_db:test_db@db:5432/test_db
      - REDIS_URL=redis://redis:6379
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
      - REFRESH_TOKEN_EXP_DAYS=7
      - ACCESS_TOKEN_EXP_SEC=5
      - ACCESS_TOKEN_SECRET=access
      - REFRESH_TOKEN_SECRET=refresh
    container_name: auth
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=test_db
      - POSTGRES_PASSWORD=test_db
      - POSTGRES_DB=test_db
    container_name: db
  redis:
    image: "redis:alpine"
    container_name: redis
