# docker-compose -f docker-compose-tests.yml up --exit-code-from web --build

version: '3.3'
services:
  web:
    build: ./web
    command: pipenv run python tests.py
    env_file:
      - ./.env.test
  db:
    image: postgres:13-alpine
    env_file:
      - ./.env.test.db
